---
- name: Catch Dynatrace Problems
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dt_api_host }}"
        dt_api_token: "{{ dt_api_token }}"
        delay: 10

  rules:

    - name: SwingSight dispatch RangeRoamer
      condition:
        any:
          - event.title == "Too many golf balls" 
          - event.payload.ProblemTitle == "Too many golf balls"
          - event.payload.ProblemTitle == "Http monitor global outage"
      action:
        run_job_template:
          name: "SwingSight | Dispatch RangeRoamer"
          organization: Default

    - name: Catch all remaining
      condition: event.meta is defined
      action:
        debug:
