- name: Go get the golf balls
  hosts: localhost
  gather_facts: false
  vars:
    dt_tenant:
    dt_token:
    swingsight_url:

  tasks:
    - name: Query the total_balls_hit metric from Dynatrace
      ansible.builtin.uri:
        url: "https://{{ dt_tenant }}/api/v2/metrics/query?metricSelector=total_balls_hit"
        method: GET
        headers:
          Authorization: "Api-Token {{ dt_token }}"
          Content-Type: "application/json"
      register: query_total_balls_hit

    - name: Update metrics
      ansible.builtin.uri:
        url: "{{ swingsight_url }}/clear-data"
        method: GET

    - name: Get problem from Dynatrace
      vars:
        title: Too many golf balls
      ansible.builtin.uri:
        url: https://{{ dt_tenant }}/api/v2/problems?problemSelector=text({{ title | urlencode }})
        method: GET
        headers:
          Authorization: "Api-Token {{ dt_token }}"
          Content-Type: "application/json"
      register: problems

    - name: Set problem_id
      ansible.builtin.set_fact:
        problem_id: "{{ problems.json.problems[0].problemId }}"

    - name: Get problem comments
      ansible.builtin.uri:
        url: https://{{ dt_tenant }}/api/v2/problems/{{ problem_id }}/comments
        method: GET
        headers:
          Authorization: "Api-Token {{ dt_token }}"
          Content-Type: "application/json"
      register: comments

    - name: Delete comments
      loop: "{{ comments.json.comments }}"
      ansible.builtin.uri:
        url: https://{{ dt_tenant }}/api/v2/problems/{{ problem_id }}/comments/{{ item.id }}
        method: DELETE
        headers:
          Authorization: "Api-Token {{ dt_token }}"
          Content-Type: "application/json"
        status_code:
          - 204
